name: muslim_app
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0


  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  font_awesome_flutter: ^10.3.0
  provider: ^6.0.4
  lottie: ^2.0.0
  shared_preferences: ^2.0.17
  share_plus: ^7.0.2
  flutter_screenutil: ^5.6.0
  audioplayers: ^5.2.0
  http: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter



  flutter_lints: ^2.0.0


flutter:
  generate: true

  uses-material-design: true
  assets:
    - assets/images/
    - assets/quran_files/
    - assets/hadith_files/
