name: 'muslim_app'
version: '1.2.1+23'
publish_to: none
environment:
  sdk: '^3.6.0'
description: A new Flutter project.
dependencies:
  audioplayers: any
  dio: ^5.8.0+1
  firebase_core: 
  firebase_remote_config: ^5.4.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  font_awesome_flutter: ^10.8.0
  http: ^1.3.0
  intl: ^0.19.0
  package_info_plus: ^8.3.0
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  url_launcher: ^6.3.1
dev_dependencies:
  build_runner: ^2.4.14
  custom_lint: ^0.7.3
  custom_lint_builder: ^0.7.3
  flutter_gen_runner: '^5.8.0'
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  pubspec_dependency_sorter: ^1.0.5
flutter:
  uses-material-design: true
  generate: true  # Ensure this is set to true
  assets:
    - assets/images/
    - 'assets/quran_files/'
    - 'assets/hadith_files/'
    - assets/Elgharib-A533.ttf
    - shorebird.yaml
  fonts:
    - family: Elgharib
      fonts:
        - asset: assets/Elgharib-A533.ttf
flutter_intl:
  enabled: true