name: 'muslim_app'
version: '1.2.1+23'
publish_to: none
environment:
  sdk: '^3.6.0'
description: A new Flutter project.
dependencies:
  audioplayers: any
  dio: ^5.8.0+1
  firebase_core: 
  firebase_performance: any
  firebase_remote_config: ^5.4.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  font_awesome_flutter: ^10.8.0
  google_mobile_ads: ^5.3.1
  http: ^1.3.0
  intl: ^0.19.0
  package_info_plus: ^8.2.1
  provider: ^6.1.2
  sentry_flutter: ^8.13.0
  shared_preferences: ^2.5.2
  url_launcher: ^6.3.1
dev_dependencies:
  custom_lint: ^0.7.3
  custom_lint_builder: ^0.7.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  pubspec_dependency_sorter: ^1.0.5
flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - 'assets/quran_files/'
    - 'assets/hadith_files/'
    - assets/Elgharib-A533.ttf
    - shorebird.yaml
    - .env
  fonts:
    - family: Elgharib
      fonts:
        - asset: assets/Elgharib-A533.ttf
flutter_assets:
  assets_path: assets/images/
  output_path: 'lib/shared/image_path/'
  filename: 'image_path.dart'
  classname: AssetsPath
flutter_intl:
  enabled: true
