name: "muslim_app"
version: 1.1.4+15
publish_to: none
environment:
  sdk: ">=3.4.4 <4.0.0"

description: A new Flutter project.

dependencies:
  audioplayers: ^6.0.0
  cupertino_icons: ^1.0.2
  dio: ^5.7.0
  firebase_analytics: ^11.3.2
  firebase_core: ^3.5.0
  firebase_crashlytics: ^4.1.2
  firebase_performance: ^0.10.0+7
  firebase_remote_config: ^5.1.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  http: ^1.1.0
  intl: ^0.19.0
  package_info_plus: ^8.0.3
  provider: ^6.0.4
  share_plus: ^10.0.0
  shared_preferences: ^2.0.17
  url_launcher: ^6.3.1

dev_dependencies:
  custom_lint: "^0.6.4"
  custom_lint_builder: "^0.6.4"
  flutter_lints: "^4.0.0"
  flutter_test:
    sdk: flutter
  pubspec_dependency_sorter: "^1.0.5"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/quran_files/
    - assets/hadith_files/
    - shorebird.yaml
flutter_assets:
  assets_path: assets/images/
  output_path: lib/shared/image_path/
  filename: image_path.dart
  classname: AssetsPath
